sector_tuner:
  ros__parameters:
    global_limit: 0.5
    n_sectors: 5
    Sector0:
      start: 0
      end: 40
      scaling: 0.5
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 41
      end: 121
      scaling: 0.5
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 122
      end: 173
      scaling: 0.5
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 174
      end: 326
      scaling: 0.5
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 327
      end: 363
      scaling: 0.5
      only_FTG: false
      no_FTG: false
