sector_tuner:
  ros__parameters:
    global_limit: 0.3
    n_sectors: 8
    Sector0:
      start: 0
      end: 10
      scaling: 0.3
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 11
      end: 66
      scaling: 0.3
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 67
      end: 82
      scaling: 0.3
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 83
      end: 170
      scaling: 0.3
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 171
      end: 195
      scaling: 0.3
      only_FTG: false
      no_FTG: false
    Sector5:
      start: 196
      end: 239
      scaling: 0.3
      only_FTG: false
      no_FTG: false
    Sector6:
      start: 240
      end: 263
      scaling: 0.3
      only_FTG: false
      no_FTG: false
    Sector7:
      start: 264
      end: 352
      scaling: 0.3
      only_FTG: false
      no_FTG: false
