sector_tuner:
  ros__parameters:
    global_limit: 0.5
    n_sectors: 6
    Sector0:
      start: 0
      end: 50
      scaling: 0.3
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 51
      end: 147
      scaling: 0.3
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 148
      end: 169
      scaling: 0.3
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 170
      end: 209
      scaling: 0.3
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 210
      end: 232
      scaling: 0.3
      only_FTG: false
      no_FTG: false
    Sector5:
      start: 233
      end: 317
      scaling: 0.3
      only_FTG: false
      no_FTG: false
