sector_tuner:
  ros__parameters:
    global_limit: 0.3
    n_sectors: 8
    Sector0:
      start: 0
      end: 17
      scaling: 0.3
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 18
      end: 66
      scaling: 0.3
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 67
      end: 97
      scaling: 0.3
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 98
      end: 170
      scaling: 0.3
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 171
      end: 203
      scaling: 0.3
      only_FTG: false
      no_FTG: false
    Sector5:
      start: 204
      end: 246
      scaling: 0.3
      only_FTG: false
      no_FTG: false
    Sector6:
      start: 247
      end: 271
      scaling: 0.3
      only_FTG: false
      no_FTG: false
    Sector7:
      start: 272
      end: 365
      scaling: 0.3
      only_FTG: false
      no_FTG: false
